nelmio_api_doc:
  areas:
    default:
      path_patterns: [ ^/api/employee ]
  documentation:
    info:
      title: Zadanie rekrutacyjne API
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: [ ]
    paths:
      /api/login_check:
        post:
          tags:
            - Login
          summary: Login endpoint
          requestBody:
            content:
              application/json:
                schema:
                  properties:
                    email:
                      example: test@test.pl
                      type: string
                    password:
                      example: zaq1@WSX
                      type: string
                  type: object
          responses:
            '200':
              description: OK
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      token:
                        type: string
                      refresh_token:
                        type: string
            '401':
              description: Invalid credentials
            '400':
              description: Invalid JSON.
          security: [ ]
